name = "esmailzaee-ir"
type = "javascript"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = []
build_watch_paths = ["app/**", "components/**", "lib/**", "public/**", "content/**"]

[env.production]
route = "esmailzaee.ir/*"
zone_name = "esmailzaee.ir"

[[analytics.engine]]
enabled = true
